### ISSUE TITLE
Error on connecting to Netflix

### ISSUE THREAD

**Issue by jwhite** [z-e-r-o/plugin.video.netflix#1]
13:32:55 T:140382549571328  NOTICE: plugin.video.netflix: Loading url: https://www.netflix.com/Login
13:32:56 T:140382549571328   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.SSLError'>
                                            Error Contents: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix-master/addon.py", line 68, in <module>
                                                general.index()
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix-master/resources/general.py", line 14, in index
                                                if login.login():
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix-master/resources/login.py", line 17, in login
                                                content = utility.decode(connect.load_site(utility.main_url + '/Login'))
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix-master/resources/connect.py", line 57, in load_site
                                                response = session.get(url, verify=True)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 480, in get
                                                return self.request('GET', url, **kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 468, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 576, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 433, in send
                                                raise SSLError(e, request=request)
                                            SSLError: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol
                                            -->End of Python script error report<--

**Comment by jwhite** [comment]
This seems related : 

http://stackoverflow.com/questions/32115607/python-3-4-ssl-error-urlopen-error-eof-occurred-in-violation-of-protocol-ssl-c

**Comment by z-e-r-o** [comment]
I implement one of the fix in the links.
Hopefully this helps you.
Otherwise give me a few more information about the client , kodi and python version you are running.
